### ISSUE TITLE
Where's 1.10.2 version?

### ISSUE THREAD

**Issue by polyzium** [daipenger/Sound-Physics#16]

**Comment by ghost** [comment]
I believe this was a fork of the 1.11 version. SonicEther appears to of removed the download link for both the resource pack and 1.10.2 version.

I'm not sure if @daipenger is planning on backwards-compatible versions with the improved code or not.

I've gone ahead and uploaded the version I had downloaded from SonicEther's Minecraft Forum post to MediaFire. Contains both the mod and the SoundFix resourcepack :) https://www.mediafire.com/?ur3crdktcdmxaqr

**Comment by polyzium** [comment]
@Artige Thank you so much! I have no idea why Sonic Ether edited his post and removed download links for 1.10.2 and earlier...

**Comment by daipenger** [comment]
Backwards compatible versions may come out when I have restructured the whole mod (which will then allow me to finally do quadratic sound fading by hand) to give out some polished versions.

Until then, resort to the link from @Artige
