### ISSUE TITLE
compile fails with updates to 1.12.1 due to class name changes

### ISSUE THREAD

**Issue by Tsoccerguy3** [daipenger/Sound-Physics#18]
class name changes from 1.12 to 1.12.1

Compiling with JDK Java compiler API.
C:\Users\ASUS\Dev\Sound-Physics\build\sources\main\java\com\sonicether\soundphysics\SPGuiFactory.java:37: error: cannot find symbol
        public RuntimeOptionGuiHandler getHandlerFor(RuntimeOptionCategoryElement element) {
               ^
  symbol:   class RuntimeOptionGuiHandler
  location: class SPGuiFactory
1 error
:compileJava FAILED
:compileJava (Thread[Daemon worker,5,main]) completed. Took 0.692 secs.

FAILURE: Build failed with an exception.

**Comment by daipenger** [comment]
I know. But you wouldn't even have a working version after solely recompiling, Sound Physics always requires the new obfuscation mappings.
Update is done.

**Comment by Tsoccerguy3** [comment]
Thank You for the update .
