### ISSUE TITLE
Volume not properly scaling with distance

### ISSUE THREAD

**Issue by ariiZona** [daipenger/Sound-Physics#20]
While there's no block between a sound source and the player, the sound always play at max or near max volume, unless you are out of range.

Here's a vid showing the problem (had to boost the brightness)
https://youtu.be/iam9HALXD0A

**Comment by ariiZona** [comment]
Just realised that this very similar with #8. But by what's said in the changelog for 1.0.4, this should be fixed right ? Then the problem may be on my side. 

Btw, all settings for the mod are default

**Comment by daipenger** [comment]
See http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2852505-sound-physics-unofficial?comment=7.
This will be done this weekend, so I am going to close it.
