### ISSUE TITLE
Update to 1.12.2?

### ISSUE THREAD

**Issue by thesilican** [daipenger/Sound-Physics#21]
It seems like this project hasn't been touched in a while, but would it be possible to update this mod to 1.12.2, the latest version as of writing? It shouldn't be too different from 1.12.1

**Comment by Bigcheese** [comment]
I just got it working in 1.12.2. All that's required is changing the version string so that forge actually loads the coremod.

**Comment by ghost** [comment]
@Bigcheese Could you enlighten me on how to do this?

**Comment by Tsoccerguy3** [comment]
mcmod.info


[
{
  "modid": "soundphysics",
  "name": "Sound Physics",
  "description": "Provides realistic sound attenuation, reverberation, and absorption through blocks.",
  "version": "1.0.4",
  "mcversion": "1.12.1",
  "url": "",
  "authorList": ["Sonic Ether","daipenger"]
}
]


 "mcversion": "1.12.1",   TO    "mcversion": "1.12.2",

I updated the mod to 1.12.2 , updated mappings and Forge as well, but the volume level is not being passed to Pauls Code , so updating just the mcmod.info wont give you reverb with 3rd party mods like Dynamic surroundings . Im looking into what i missed . Maybe Greg will fix it

**Comment by VirtualGaming1** [comment]
I hope this get updated to 1.12.2 soon i loved this mod and miss it

**Comment by stjak** [comment]
@Tsoccerguy3 I changed the version string, and while the mod loads in 1.12.2, it doesn't really work. The game just sounds like default Minecraft. Is it working properly for you?

**Comment by Bigcheese** [comment]
```
diff --git a/build.gradle b/build.gradle
index 5a875f1..2b0a44a 100644
--- a/build.gradle
+++ b/build.gradle
@@ -10,7 +10,7 @@ buildscript {
 apply plugin: 'net.minecraftforge.gradle.forge'
 //Only edit below this line, the above code adds and enables the necessary things for Forge to be setup.

-version = "1.12.2"
+version = "1.12.1"
 archivesBaseName = "Sound-Physics"

 jar {
@@ -26,9 +26,9 @@ compileJava {
 }

 minecraft {
-    version = "1.12.2-14.23.0.2512"
+    version = "1.12.1-14.22.1.2481"
     runDir = "run"
-    mappings = "snapshot_20171003"
+    mappings = "snapshot_20170624"
 }

 dependencies {
diff --git a/src/main/resources/mcmod.info b/src/main/resources/mcmod.info
index 8241d74..a9f32e5 100644
--- a/src/main/resources/mcmod.info
+++ b/src/main/resources/mcmod.info
@@ -4,7 +4,7 @@
   "name": "Sound Physics",
   "description": "Provides realistic sound attenuation, reverberation, and absorption through blocks.",
   "version": "1.0.4",
-  "mcversion": "1.12.2",
+  "mcversion": "1.12.1",
   "url": "",
   "authorList": ["Sonic Ether","daipenger"]
 }
```

I also have other changes, but I'm pretty sure they aren't needed.

**Comment by stjak** [comment]
Thank you very much, @Bigcheese. It is working fully now!

**Comment by daipenger** [comment]
Updated

**Comment by thesilican** [comment]
Thanks :)
I can finish my modpack now
