### ISSUE TITLE
Permission to upload with my modpack on Curse?

### ISSUE THREAD

**Issue by VirtualGaming1** [daipenger/Sound-Physics#22]
Hay since you updated to 1.12.2 that I would like to ask you that if i can have this on my modpack and upload it to Curse. This Pack is called Real Life Modpack and is only able to get it on Twitch app.

**Comment by VirtualGaming1** [comment]
can i get a reply back at least i been waiting

**Comment by Lorelando** [comment]
If you read through the LICENSE file, everything should become pretty clear (https://github.com/daipenger/Sound-Physics/blob/master/LICENSE).

**Comment by VirtualGaming1** [comment]
Thanks
