### ISSUE TITLE
1.12.2 is not working with Dynamic Surrounding , Footsteps

### ISSUE THREAD

**Issue by Tsoccerguy3** [daipenger/Sound-Physics#23]
Dynamic Surrounding , Footsteps are muted or volume not passed on to Pauls code

**Comment by Endmateria** [comment]
The footsteps are making sound at y=31 and below, while they are silent at y=32 and above.

**Comment by Tsoccerguy3** [comment]
This issue is fixed By OreCruncher in the most recent Dynamicsurroundings
