### ISSUE TITLE
Simply Jetpack 2 sounds can be heard server wide

### ISSUE THREAD

**Issue by MrFastZombie** [daipenger/Sound-Physics#25]
When we were using it, we could hear simply jetpacks 2 sounds even when we were far away from each other. Had to disable the sounds in the config.

**Comment by Lorelando** [comment]
Most issues I had with sounds I could resolve by going into the mods jar file and editing the specific sound file to be mono with Audacity.
Just in case you need a quick workaround.

**Comment by MrFastZombie** [comment]
Also happens with other mods, such as Immersive Engineering, with the diesel generator.

**Comment by daipenger** [comment]
Duplicate of #8 
As 1.0.4 rolled back that fix, the release notes state: You have to convert all your custom sounds to mono again!

[djpadbit/Sound-Physics](https://github.com/djpadbit/Sound-Physics) is my current recommendation.
