### ISSUE TITLE
SoundPhysics behaving weird combined with Dynamic Surroundings mod

### ISSUE THREAD

**Issue by J3LL4** [daipenger/Sound-Physics#26]
Some sounds are barely hearable, and some are very loud. Footsteps are always playing in player position, even when its a mob. Is there a way to fix it?

**Comment by Lorelando** [comment]
This is probably the same bug as #25.
If you modify the footstep sound to be mono (eg with Audacity) instead of stereo, it should fix the problem.

**Comment by daipenger** [comment]
Duplicate of #8 and #25
As 1.0.4 rolled back that fix, the release notes state: You have to convert all your custom sounds to mono again!

[djpadbit/Sound-Physics](https://github.com/djpadbit/Sound-Physics) is my current recommendation.
