### ISSUE TITLE
Sound fix resourcepack download link is expired

### ISSUE THREAD

**Issue by whffktkw** [daipenger/Sound-Physics#28]
Can i get other link for resourcepack?

**Comment by Lorelando** [comment]
You should try [djpadbit's Sound-Physics ](https://github.com/djpadbit/Sound-Physics)fork, he implemented a stereo to mono conversion, making the soundpack redundant.

**Comment by daipenger** [comment]
I still have the soundfix resourcepack, but @Lorelando's solution is my current recommendation.
If someone, for some rare reason, still needs the resourcepack, message me.

**Comment by ghost** [comment]
@daipenger I need this resourcepack. Give me the link please.
