### ISSUE TITLE
Update to 1.12

### ISSUE THREAD

**Issue by JAD3N** [daipenger/Sound-Physics#6]
I would love to see this mod continually updated. A pull request should be soon.

**Comment by daipenger** [comment]
I actually started the progress of updating yesterday. But I don't have a lot of free time currently so it may take some days. As you mentioned a pull request: Should I wait for you?

**Comment by JAD3N** [comment]
I have a functioning update ready, testing as we speak.

**Comment by JAD3N** [comment]
Pull request sent, more testing needed but I think it's working as intended. #7

**Comment by daipenger** [comment]
I double checked the mappings, everything seems correct.
Quick test also showed no new problems.
Nice, thanks for the help! 👍 Releasing now.
